version: '3'
services:
  edge_service:
    build: .
    image: tyhjataulu/go-edge-api:x86
    ports:
      - 8080:8080
    privileged: true
    deploy:
      mode: global
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 10M
      placement:
        constraints:
          - node.labels.location == edge
          - node.labels.arch == x86