version: '2.2'
services:
  edge_service:
    build: .
    image: tyhjataulu/go-blinker:latest
    ports:
      - "8080:8080"
    deploy:
      devices:
        - "/dev/gpiomem:/dev/gpiomem"
      replicas: 2
      placement:
        constraints:
          - node.labels.location == edge