version: '3'
services:
  edge_service:
    build: .
    image: tyhjataulu/go-blinker:latest
    ports:
      - 8080:8080
    privileged: true
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.location == edge
          - node.labels.arch == arm

  msg_broker:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    deploy:
      mode: global
      placement:
        constraints:
          - hostname == raspi3