version: '3'
services:
  edge_service:
    build: .
    image: tyhjataulu/go-blinker:latest
    ports:
      - "8080:8080"
    privileged: true
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.location == edge