version: '3'
services:
  edge_service:
    build: .
    image: tyhjataulu/go-blinker:latest
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.location == edge